# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4263dd63cd392f16e711b804a67500cbe5a5f4e6e17836e48fb3e4857963c3b39a14815ebbfc93375648d96a3a6e4a3de062a4cb452f60aaf98cc5dd429680b

test:
  secret_key_base: 537a91ae6b3f2d7c6ac9183e33881b8d3add6fa942d1f955f60e3091161b1c16e7fc968b4b4c5cd994a6103af494b59abd20884b9edf8f432f681c5a58494a24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
